# Generated by Django 3.0 on 2019-12-26 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
                ('author_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
